### ISSUE TITLE
NHD-C160100DiZ.ino on 32-bit ARM Cortex-M0+ microcontroller

### ISSUE THREAD

**Issue by blankenshipbotron** [NewhavenDisplay/NHD-C160100DiZ_Example#1]
Hi,
Thanks for your code example. I tried running on a SAMD21 ARM M0 processor and I was having problems.
I fixed it by putting the following in the Setup function

  //DDRA = 0xFF;   // need to uncomment
  //DDRD = 0xFF;  // need to uncomment
  pinMode(RST, OUTPUT);
  pinMode(CS, OUTPUT);
  pinMode(SDA, OUTPUT); // need to ADD set to output
  pinMode(SCL, OUTPUT); // need to ADD set to output

Thanks again for the code.
mike

**Comment by CJoh-NHD** [comment]
@blankenshipbotron Thanks for the information. 
Glad to see you got it working with your processor.
